version: 2

jobs:

  #   python2:
  #     working_directory: ~/meshio
  #     docker:
  #       - image: ubuntu:17.10
  #     steps:
  #       - run: apt-get update
  #       - run: apt-get install -y git python-h5py python-numpy python-vtk6 python-pip
  #       - run: pip2 install -U pytest pytest-cov pylint
  #       - checkout
  #       - run: pip2 install .
  #       # The actual test
  #       - run: pylint meshio/
  #       - run: pylint test/*py
  #       # No Exodus tests on VTK6 -- they segfault
  #       - run: rm -f test/test_exodus.py
  #       # XDMF3 is not part of VTK6
  #       - run: rm -f test/test_xdmf3.py
  #       # ASCII VTK tests fail with Python2/VTK6
  #       - run: rm -f test/test_vtk.py
  #       - run: cd test/ && pytest --cov meshio

#  python3:
  build:
    working_directory: ~/meshio
    docker:
      - image: ubuntu:17.10
    steps:
      - run: apt-get update
      - run: apt-get install -y software-properties-common
      - run: LANG=C.UTF-8 apt-add-repository -y ppa:nschloe/vtk7
      - run: apt-get update
      - run: apt-get install -y git python3-h5py python3-netcdf4 python3-vtk7 python3-pip
      - run: pip3 install -U pytest pytest-cov pylint
      - checkout
      - run: pip3 install .[exodus,hdf5]
      # Make sure to get numpy 1.13.0
      - run: pip3 install -U numpy
      # make sure that rst converts correctly
      - run: apt install -y pandoc
      - run: pip3 install docutils pygments
      - run: make README.rst
      - run: python3 setup.py check -r -s
      # The actual test
      - run: pylint meshio/
      - run: pylint test/*py
      - run: pylint tools/meshio-convert
      - run: cd test/ && pytest --cov meshio
      # submit to codecov
      - run: apt-get install -y curl
      - run: bash <(curl -s https://codecov.io/bash)

# workflow builds don't support forked PRs yet, cf.
# <https://circleci.com/docs/2.0/faq/#can-i-build-fork-prs-using-workflows>.
# workflows:
#   version: 2
#   build-and-test:
#     jobs:
#       - python2
#       - python3
